"""Adiciona telefone e observacoes em users

Revision ID: 470de1be7c45
Revises: 962d481e11f2
Create Date: 2026-08-04 20:10:10.872748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470de1be7c45'
down_revision = '962d481e11f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
