"""Adiciona campo is_active em users

Revision ID: 962d481e11f2
Revises: f5b156e319f1
Create Date: 2026-08-03 20:49:34.072080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962d481e11f2'
down_revision = 'f5b156e319f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_active',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'is_active',
            server_default=None
        )
    # ### end Alembic commands ###

def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###        
